set -g default-terminal "foot"

set -g mouse on
set -g default-command "${SHELL}"
set -g status-position top
set -g status-style bg=default
set -g status-justify "absolute-centre"

set -g status-right '#(whoami)@#H %H:%M %d-%b-%Y'
set -g status-left-length 40
set -g status-left "#S"

unbind C-b
set -g prefix M-a
bind M-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n C-PAGEDOWN next-window
bind -n C-PAGEUP previous-window

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g @yank_selection 'primary'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run '~/.tmux/plugins/tpm/tpm'

